# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font Mono"
font_size        11.0
background_opacity 0.85
scrollback_lines 10000
enable_audio_bell no
bold_font        auto
italic_font      auto
bold_italic_font auto

# WINDOWS
window_margin_width 4
window_border_width 2pt

# ARCH_SPECIFIC
linux_display_server x11

# USE_DEFAULT_SHELL
shell .

# USE_DEFAULT_EDITOR
editor .

# TAB_BAR_STYLING:
tab_bar_min_tabs 1
tab_bar_edge bottom
tab_bar_margin_height 4.0 4.0
tab_bar_margin_width 4.0
tab_bar_style powerline
tab_powerline_style round

# COMMAND_NOTIFICATIONS:
notify_on_cmd_finish invisible 15

# URL_HANDLING:
allow_hyperlinks yes
url_color #0087bd
url_style dotted
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
open_url_with default
detect_urls yes
show_hyperlink_targets yes
underline_hyperlinks always
copy_on_select no
